### ISSUE TITLE
bug synchronise

### ISSUE THREAD

**Issue by ortegalex** [meniga/mobile-sdk-ios#25]
On MNFSynchronization class, on p_querySynchronizationWithSync function, sync.isSyncDone is NSNumber and always return true when check if the value is true or false.

**Comment by hoikuru** [comment]
Thanks for flagging this. A fix is in PR https://github.com/meniga/mobile-sdk-ios/pull/26

**Comment by ortegalex** [comment]
And this line too:
if (fabs(timeoutInterval) > [timeout doubleValue]/1000 && !sync.isSyncDone) {
