### ISSUE TITLE
Generate comma separated string don't work correctly 

### ISSUE THREAD

**Issue by ortegalex** [meniga/mobile-sdk-ios#31]
On MNFMerchant class, on fetchMerchantsWithIds procedure, the first loop does not work correctly. 
Passing this series as parameter: 12 12 12 34 45 65 12
The result string is: 12121234,45,65,12
And must be: 12,12,12,34,45,65,12

**Comment by hoikuru** [comment]
https://github.com/meniga/mobile-sdk-ios/pull/33

**Comment by WezSieTato** [comment]
Fixed on version 1.1.13
