### ISSUE TITLE
Does iOS Meniga SDK include deprecated UIWebView?

### ISSUE THREAD

**Issue by Gagan5278** [meniga/mobile-sdk-ios#57]
Hi Team,

Could you please confirm whether iOS Meniga SDK contains UIWebView or not?

**Comment by Dentro2000** [comment]
Hi Gagan5278,

iOS Meniga SDK does not contain UIWebView.

**Comment by Gagan5278** [comment]
Thanks For your reply. Hope older versions also do not have UIWebView

**Comment by Dentro2000** [comment]
Older versions also do not include UIWebView.

**Comment by Gagan5278** [comment]
Thank you so much. Really appreciate your quick reply.
